### PR TITLE
Fix incorrect batch creation logic in MultiBatchBuffer

### PR DESCRIPTION
**Pull request by AndreasAlbert**
MultiBatchBuffer problem:
1. The buffer returned incorrectly sized batches (off-by-one error).
2. The buffer returned batches that had overlapping events in them as a result of incorrect indices being used. 

Specifically example: if the full data is ```[1,2,3,4,5,...]``` and `batch_size=3`, the buffer returned a first batch ```[1, 2, 3, 4]```, and then a second batch ```[2,3,4,5]```

Thanks @alpakpinar for finding this bug and proposing a solution.

### CODE REVIEW

**Comment by alpakpinar** [comment]
Hi @AndreasAlbert , thanks so much for the fix and adding this to the tests! I just had one edge-case issue: Can we make sure that the `row_start` parameter is an `int`? I believe for the case where we pick a `batch_size > len(df)`, the `row_start` ends up being a `float`, and `pandas` does not accept that for `iloc[]`. Thanks so much!

**Comment by AndreasAlbert** [comment]
Currently unclear where this float would be originating from. Merging this PR because the change is urgent. Once we figure out where the float problem comes from, will make a new PR.

**Comment by alpakpinar** [comment]
Just a follow-up: This should not be an issue on the sequence code itself, in the edge-case I specified earlier `batch_size` was accidentally given a `float` value.

**Review by Gabriel-Gotti — COMMENTED** [review]
Duplicate of #

**Pull request merged**
